# utilities/retrieve_secret.py
import requests
import json
import sys

# --- VAULT CONFIGURATION ---
VAULT_ID = "23A91A6160"
VAULT_REPO = "https://github.com/karthikthorlapati/pki-2fa-microservice"
# The Gateway URL remains the same
GATEWAY_URL = "https://eajeyq4r3zljoq4rpovy2nthda0vtjqf.lambda-url.ap-south-1.on.aws/"
# ---------------------------

def execute_retrieval():
    try:
        # Load the Public Identity generated by identity_gen.py
        with open("identity_public.pem", "r") as key_file:
            public_identity_data = key_file.read()

        # Construct payload (Keys must match API requirements)
        payload = {
            "student_id": VAULT_ID,
            "github_repo_url": VAULT_REPO,
            "public_key": public_identity_data
        }

        print(f"Authenticating Vault ID {VAULT_ID} with Gateway...")
        response = requests.post(GATEWAY_URL, json=payload)
        
        if response.status_code == 200:
            data = response.json()
            if "encrypted_seed" in data:
                # Save the locked seed to the new filename
                with open("locked_seed.dat", "w") as secret_file:
                    secret_file.write(data["encrypted_seed"])
                print(">> Locked seed secured in 'locked_seed.dat'")
            else:
                print("!! Gateway Error:", data)
        else:
            print(f"!! Connection Error {response.status_code}: {response.text}")

    except Exception as error:
        print(f"!! System Failure: {error}")

if _name_ == "_main_":
    execute_retrieval()